# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
            options={
                'db_table': 'visits',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('last_name', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('matches_won', models.IntegerField(editable=False, default=0)),
                ('matches_played', models.IntegerField(editable=False, default=0)),
                ('win_rate', models.IntegerField(editable=False, default=0)),
                ('standing', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.IntegerField(primary_key=True)),
                ('winner_first_name', models.CharField(max_length=10)),
                ('winner_last_name', models.CharField(max_length=10)),
                ('loser_first_name', models.CharField(max_length=10)),
                ('loser_last_name', models.CharField(max_length=10)),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('day', models.DateField()),
                ('points', models.IntegerField(editable=False)),
                ('winner_rating', models.IntegerField(editable=False)),
                ('loser_rating', models.IntegerField(editable=False)),
            ],
            options={
                'db_table': 'matches',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
