# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_history',
                'verbose_name_plural': 'Attendance History',
            },
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'practices',
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
