# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_attendancehistory_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancehistory',
            name='Late',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='clubattendance',
            name='Time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 7, 17, 30, 35, 718063, tzinfo=utc), verbose_name=b'date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='Lateness',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
