# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20161007_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Standing',
            field=models.IntegerField(choices=[(1, b'Freshman'), (2, b'Sophomore'), (3, b'Junior'), (4, b'Senior'), (5, b'Grad')]),
        ),
    ]
