# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20161007_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Standing',
            field=models.IntegerField(choices=[(1, b'Freshman'), (2, b'Sophomore'), (3, b'Junior'), (4, b'Senior'), (5, b'Grad'), (6, b'Unknown')]),
        ),
    ]
