# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20170122_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='practices',
            name='Count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
