# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-22 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='Date',
            field=models.DateField(),
        ),
    ]
