# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20170221_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='LastSeen',
            field=models.DateField(default=datetime.datetime(2017, 2, 23, 4, 53, 21, 297081, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
