# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-25 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_players_lastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'slides',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.AlterField(
            model_name='players',
            name='LastSeen',
            field=models.DateField(default=datetime.date(2017, 3, 25), editable=False),
        ),
    ]
