# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-25 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20170325_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='Date',
            field=models.DateField(default=datetime.date(2017, 3, 25)),
            preserve_default=False,
        ),
    ]
