# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-25 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_slides_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slides',
            old_name='URL',
            new_name='SlidesID',
        ),
    ]
