# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-25 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20170325_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='SlidesID',
            field=models.CharField(max_length=100),
        ),
    ]
