# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_auto_20170327_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'images',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
