# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Page',
            field=models.IntegerField(choices=[(1, b'background'), (2, b'index'), (3, b'attendance'), (4, b'summary'), (5, b'ladder'), (6, b'about'), (7, b'rules'), (8, b'contact')]),
        ),
    ]
