# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20170327_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'location',
                'verbose_name_plural': 'Location',
            },
        ),
    ]
