# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0020_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Name', models.CharField(max_length=100)),
                ('Organization_Email', models.CharField(max_length=100)),
                ('Organization_Facebook', models.CharField(max_length=100)),
                ('Organization_Bengaged', models.CharField(max_length=100)),
                ('Organization_Youtube', models.CharField(max_length=100)),
                ('Organization_Address1', models.CharField(max_length=100)),
                ('Organization_Address2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organization_information',
                'verbose_name_plural': 'Organization Information',
            },
        ),
    ]
