# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_organizationinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancehistory',
            options={'verbose_name_plural': 'Past Attendance'},
        ),
        migrations.AlterField(
            model_name='players',
            name='LastSeen',
            field=models.DateField(default=datetime.date(2017, 3, 28), editable=False),
        ),
    ]
