# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_auto_20170327_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinformation',
            name='Other_Website_Logo',
            field=models.CharField(default='http://imgur.com/I94Lg9M.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='Year_First_Established',
            field=models.CharField(default=2016, max_length=10),
            preserve_default=False,
        ),
    ]
