# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_auto_20170327_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
