# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'front_page_content',
                'verbose_name_plural': 'Front Page Content',
            },
        ),
        migrations.AddField(
            model_name='organizationinformation',
            name='Description',
            field=models.CharField(default='Hello', max_length=500),
            preserve_default=False,
        ),
    ]
