# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_auto_20170328_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_URL', models.CharField(max_length=100)),
                ('Logo_URL', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'social_media',
                'verbose_name_plural': 'Social Media',
            },
        ),
    ]
