# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0028_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinformation',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='organizationinformation',
            name='Other_Website',
        ),
        migrations.RemoveField(
            model_name='organizationinformation',
            name='Other_Website_Logo',
        ),
        migrations.RemoveField(
            model_name='organizationinformation',
            name='Youtube',
        ),
    ]
