# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_auto_20170328_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='LastSeen',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
