# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_auto_20170328_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(choices=[(b'#ff0000', b'Red'), (b'ffa500', b'Orange'), (b'ffff00', b'Yellow'), (b'#007451', b'Green'), (b'#0000ff', b'Blue'), (b'#4b0082', b'Indigo'), (b'#8a2be2', b'Violet'), (b'#808080', b'Gray'), (b'#000000', b'Black')], max_length=10)),
            ],
            options={
                'db_table': 'color_scheme',
                'verbose_name_plural': 'Color Scheme',
            },
        ),
    ]
