# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0033_auto_20170329_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubattendance',
            options={'verbose_name_plural': 'Old Attendance'},
        ),
    ]
