# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0034_auto_20170329_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancehistory',
            options={'verbose_name_plural': 'Club Attendance'},
        ),
    ]
