# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0036_auto_20170329_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancehistory',
            old_name='Late',
            new_name='Updated',
        ),
    ]
