# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0038_auto_20170330_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancehistory',
            name='Email',
            field=models.CharField(blank=True, help_text=b'Enter your email here if you wish to join the mailing list', max_length=100),
        ),
    ]
