# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_attendancehistory_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancehistory',
            name='Email',
            field=models.CharField(blank=True, help_text=b'Optional: Enter your email here if you wish to join the mailing list', max_length=100),
        ),
    ]
