# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0041_players_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancehistory',
            name='Class_Standing',
            field=models.CharField(blank=True, choices=[(b'Freshman', b'Freshman'), (b'Sophomore', b'Sophomore'), (b'Junior', b'Junior'), (b'Senior', b'Senior'), (b'Grad', b'Grad')], help_text=b'Optional: Select your class standing', max_length=10),
        ),
    ]
