# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0043_auto_20170404_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='Position',
            field=models.IntegerField(choices=[(1, b'President'), (2, b'Co-President'), (3, b'Treasurer'), (4, b'Secretary'), (5, b'Webmaster'), (6, b'Treasurer/Secretary')]),
        ),
    ]
