# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0045_colorscheme_bodylinkcolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Site Images'},
        ),
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name_plural': 'Photos'},
        ),
    ]
