# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0047_auto_20170418_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='Loser_Score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Winner_Score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
