# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0049_auto_20170419_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='Loser_Score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], help_text=b'Number of sets won'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='Winner_Score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], help_text=b'Number of sets won'),
        ),
    ]
