# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0050_auto_20170419_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eboard',
            name='Position',
            field=models.CharField(max_length=50),
        ),
    ]
